### ISSUE TITLE
rule: enable properties sort (and see what happens)

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/eslint-config-firecloud#11]

**Comment by andreineculau** [comment]
I veto this.

**Comment by IanSavchenko** [comment]
Ok, I tried it out. Nothing really bad (except for 300+ vioations in atex alone 😄), but I see why it is not so good. Sometimes, the order matters when you want to put some properties higher than others like 
```js
request({
 headers: [..],
 body: myBody
})
```

What I can imagine is to have a more "lightweight" version of the rule, where it applies only in cases of plane object destruction and object literal when no values are assigned like these:
```js
let {a, b, c} = d;
let e = {
 f,
 g,
 h
}
```
(not apply for cases like)
```js
let { a: alias, b, c} = d;

let e = {
 n: name,
 f: file,
 a
}
```

Also, just have it as a warning. So if there will be a "monotonous" set of identifiers, it will be sorted. Maybe, I will get some inspiration later.
