### ISSUE TITLE
underscore prefix only in files with "export" syntax

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/eslint-config-firecloud#12]
if a file is not a module, but a "global"=script, then the 2 rules should not require the existence or the lack of underscore prefix

PS: only the `export` keyword, not the `exports/module.exports` variable

**Comment by IanSavchenko** [comment]
Fixed with f46157b9a7bd65e429066fec5bc74be8b8424da7

**Comment by andreineculau** [comment]
fyi https://help.github.com/articles/closing-issues-using-keywords/
