### ISSUE TITLE
rule change: allow oneliner arrow functions

### ISSUE THREAD

**Issue by semikolon** [tobiipro/eslint-config-firecloud#14]
The rule name is **arrow-body-style**

I want to be able to do
```
    labels: _.map(results, (r) => r[`${brand}_brand`]),
```
instead of
```
    labels: _.map(results, (r) => {
      return r[`${brand}_brand`];
    }),
```

Kind of like being able to do oneliners like these, it's a feature of the new arrow function syntax :)

**Comment by IanSavchenko** [comment]
It's a "no" from me. Visually it is easier to see args and function body when they are on different lines. When you (I mean anyone who writes code) know that one-liners are not allowed, you won't be trying to squeeze logic into a one-liner and will keep the code readable. 
It can be mentioned here, that usage of fat-arrow functions has to be justified by using some other of their qualities (like context capturing) not just syntax sugar and less typing (6 characters difference?).
