### ISSUE TITLE
Discuss import/exports-last

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/eslint-config-firecloud#5]
Quite annoying rule, considering how we like to wrap top-level functions with `throttle` or `bootstrap` (in case of atex-platform). I don't think the situation is that bad that we abuse breaking the rule sometimes for a better readability.

**Comment by andreineculau** [comment]
I was also thinking about this rule :)
But you're not thinking of having a private or _prefixed exported fun that is non-throttled ?

```js
export let _fun = function() {...};

export let fun = _.throttle(_fun, ...);
```

**Comment by IanSavchenko** [comment]
That's an option, but we plan to stop marking _private with `export` keyword. So then throttled version declaration will be separated somewhere at the bottom of the file. Not that it's impossible, but that's a considerable refactoring :)
I'm ok with either solution of keeping the rule or not, but if we keep it, then it's good to agree on a new style. Just to mention, I would like to avoid "cabbages" like ```export let func = _.throttle(bootstrap(function { ...})); ```
