### ISSUE TITLE
rule: check not-exported variables are prefixed with _

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/eslint-config-firecloud#6]
given https://github.com/tobiipro/babel-preset-firecloud/issues/2 is fixed, we need to make sure that inside a module

* a top-level variable that is not exported is prefixed with _
* a top-level variable that is exported is not prefixed with _

**Comment by IanSavchenko** [comment]
Fixed with 380a06c3e7f355d4d14be6c507bda096f02daac2
